---
downstream_package_name: rust-pretty-git-prompt
srpm_build_deps:
- cargo
- cargo-rpm-macros
actions:
  create-archive:
    # didn't manage to make it work with --offline, cargo cannot find the packages/crates locally
  - cargo package --allow-dirty
  - bash -c "ls -1 target/package/*.crate"
jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: tests
    trigger: pull_request
    targets:
      - fedora-latest
      - fedora-rawhide

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
