# Generated by rust2rpm
%bcond_without check

%global crate pretty-git-prompt

Name:           rust-%{crate}
Version:        0.2.1
Release:        %autorelease
Summary:        Your current git repository information inside a beautiful shell prompt

License:        MIT
URL:            https://crates.io/crates/pretty-git-prompt
Source0:        %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 23

%description
%{summary}.

%package     -n %{crate}
Summary:        %{summary}
# MIT
# MIT AND GPL-2.0-only WITH GCC-exception-2.0 AND BSD-3-Clause
# MIT OR Apache-2.0
# MIT OR Apache-2.0 OR Zlib
# Zlib OR Apache-2.0 OR MIT
License:        MIT AND BSD-3-Clause AND GPL-2.0-only WITH GCC-exception-2.0 AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR Zlib)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate}
%{summary}.

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%cargo_license_summary
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
# https://github.com/tomastomecek/pretty-git-prompt/issues/35
%cargo_test || :
%endif

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%doc files
%{_bindir}/pretty-git-prompt

%changelog
%autochangelog
